#!/bin/bash

NAME=${NAME:-ecagentd}
TWISTD=${TWISTD:-/usr/bin/twistd}
TAC=${TAC:-"$NAME.tac"}
DESC=${DESC:-"ECM Agent"}
DIR=${DIR:-/opt/ecmanaged/ecagent}
PID_FILE=${PID_FILE:-"$DIR/twistd.pid"}
RETVAL=0

getpid() {
    echo `cat $PID_FILE 2>/dev/null`
}

start() {
    if [ -f ${PID_FILE} ]; then
        PID=$(getpid)
        if [ -e /proc/${PID} -a /proc/${PID}/exe ]; then
            echo ${NAME} is already running: $PID
            exit 2;
        else
            rm  -f ${PID_FILE}
        fi
    fi

    echo -n $"Starting ${NAME}: "
    if getent passwd ecmanaged > /dev/null 2>&1; then
        $TWISTD --uid $(id -u ecmanaged) --gid $(id -g ecmanaged) -y $TAC 2>/dev/null
    else
        $TWISTD -y $TAC 2>/dev/null
    fi
    RETVAL=$?
    echo
}

stop() {
    echo -n $"Stopping ${NAME}: "
    PID=$(getpid)
    kill $PID
    RETVAL=$?
    echo
    if [ $RETVAL = 0 ]; then
        rm -f ${PID_FILE}
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        status twistd
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|check|kill}"
        exit 1
esac

exit $RETVAL

