#!/bin/sh
systemctl daemon-reload
systemctl enable ecagentd.service
systemctl daemon-reload

chown -R ecmanaged:ecmanaged /opt/ecmanaged
mkdir -p /etc/ecmanaged
chown -R ecmanaged:ecmanaged /etc/ecmanaged

systemctl start ecagentd.service >/dev/null 2>&1