#!/bin/sh

set -e

getent group ecmanaged >/dev/null || groupadd -r ecmanaged
getent passwd ecmanaged >/dev/null || \
    useradd -r -g ecmanaged -d /opt/ecmanaged -s /usr/sbin/nologin \
    -c "account for running ecagent" ecmanaged

case "$1" in
    upgrade)
    # Stop the service if we're upgrading
    if [ -f /etc/init.d/ecagentd ]; then
        /etc/init.d/ecagentd stop
        if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
            dpkg-maintscript-helper rm_conffile /etc/init.d/ecagentd -- "$@"
        fi
    fi

    if which systemctl >/dev/null 2>&1; then
        if systemctl list-units | grep ecagentd >/dev/null 2>&1; then
            systemctl stop ecagentd.service
            systemctl disable ecagentd.service
            if [ -f /usr/lib/systemd/system/ecagentd.service ]; then
                if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
                    dpkg-maintscript-helper rm_conffile /usr/lib/systemd/system/ecagentd.service -- "$@"
                fi
            fi

            if [ -f /lib/systemd/system/ecagentd.service ]; then
                if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
                    dpkg-maintscript-helper rm_conffile /lib/systemd/system/ecagentd.service -- "$@"
                fi
            fi
            systemctl daemon-reload
        fi
    fi

    if [ -f /etc/cron.d/ecmanaged-ecagent ]; then
        if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
            dpkg-maintscript-helper rm_conffile /etc/cron.d/ecmanaged-ecagent -- "$@"
        fi
    fi

    if [ -f /opt/ecmanaged/ecagent/init ]; then
        /opt/ecmanaged/ecagent/init stop 2>&1
    fi

esac
