#!/bin/sh

set -e

getent group ecmanaged >/dev/null || groupadd -r ecmanaged
getent passwd ecmanaged >/dev/null || \
    useradd -r -g ecmanaged -d /opt/ecmanaged -s /usr/sbin/nologin \
    -c "account for running ecagent" ecmanaged

case "$1" in
    upgrade)
    # Stop the service if we're upgrading
    if [ -f /etc/init.d/ecagentd ]; then
        /etc/init.d/ecagentd stop
    else
        systemctl stop ecagentd.service
    fi

    if which systemctl >/dev/null 2>&1; then
        if [ -f /etc/init.d/ecagentd ]; then
            if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
                dpkg-maintscript-helper rm_conffile /etc/init.d/ecagentd -- "$@"
            fi
        fi
    fi

    if [ -f /etc/cron.d/ecmanaged-ecagent ]; then
        rm -f /etc/cron.d/ecmanaged-ecagent >/dev/null 2>&1
    fi
esac
